import { Form, Input, Modal } from "antd";
import { AppButton } from "components/button/AppButton";
import { IModalProps } from "types";
import { generalValidationRules } from "utils/formHelpers/validation";
import { TAction } from "../types";

interface DisableTwoFAProps extends IModalProps {
    setAction: (action: TAction) => void;
  }

export const DisableTwoFA = ({ open, handleClose, setAction }: DisableTwoFAProps) => {
  const [form] = Form.useForm();

  const handleFormSubmit = (values: any) => {
    console.log(values);
  };

  return (
    <>
    <Modal
      open={open}
      footer={null}
      onCancel={() => handleClose()}
      title={`Disable Two-Factor Authentication`}
    >
      <div className="text-center pt-5">
        <p>
          To disable 2FA, enter the 6-digit verification code generated by{" "}
          <br className="md:flex hidden" /> your authenticator app below
        </p>

        <Form
          onFinish={handleFormSubmit}
          form={form}
          layout="vertical"
          className="mt-4"
          requiredMark={false}
        >
          <Form.Item name="digits" rules={generalValidationRules}>
            <Input.OTP formatter={(str) => str.toUpperCase()} />
          </Form.Item>

          <div className="flex justify-between mt-3">
            <p  onClick={() => setAction("use-backup-codes")} className="text-[#01966B] font-medium cursor-pointer">
              Use a backup code instead
            </p>
            <AppButton label="Disable" type="submit" />
          </div>
        </Form>
      </div>
    </Modal>
    </>
  );
};
