import { Form, Input, Modal } from "antd";
import { AppButton } from "components/button/AppButton";
import { IModalProps } from "types";
import { generalValidationRules } from "utils/formHelpers/validation";

export const GenerateBackupCodes = ({ open, handleClose }: IModalProps) => {
  const [form] = Form.useForm();

  const handleFormSubmit = (values: any) => {
    console.log(values);
  };

  return (
    <Modal
      open={open}
      footer={null}
      onCancel={() => handleClose()}
      title={`Generate Backup Code`}
    >
      <div className="text-center pt-5">
        <p>
          To generate new backup codes, enter the 6-digits verification{" "}
          <br className="md:flex hidden" /> code generated by your authenticator
          app.
        </p>

        <Form
          onFinish={handleFormSubmit}
          form={form}
          layout="vertical"
          className="mt-4"
          requiredMark={false}
        >
          <Form.Item name="digits" rules={generalValidationRules}>
            <Input.OTP formatter={(str) => str.toUpperCase()} />
          </Form.Item>

          <div className="flex justify-end">
            <AppButton label="Continue" type="submit" />
          </div>
        </Form>
      </div>
    </Modal>
  );
};
