export type TSinglePayslip = {
  id: number;
  payrollId: number;
  employeeId: number;
  email: string;
  empUid: string;
  eligibility: string;
  fullName: string;
  gender: string;
  netPay: string;
  grossPay: string;
  totalAllowances: string;
  totalDeductions: string;
  tax: string;
  leaveAllowance: string;
  itf: string;
  nsitf: string;
  overtime: string;
  pension: string;
  thirteenthMonthSalary: string;
  costCentre: string;
  currency: string;
  exchangeRate: string;
  ytdNet: string;
  ytdGross: string;
  ytdTax: string;
  phoneNumber: string;
  branch: string;
  department: string;
  designation: string;
  accountNumber: string;
  bankName: string;
  bankCode: string;
  hourlyRate?: any;
  hoursCompleted: number;
  itfAuthority: string;
  itfId: string;
  nin: string;
  nsitfAuthority: string;
  nsitfId: string;
  pensionAdministrator: string;
  pensionId: string;
  taxAuthorityName: string;
  taxId: string;
  payrollType: string;
  confirmedAt: string;
  isActive: boolean;
  companyId: number;
  createdAt: string;
  updatedAt: string;
  employeeSalaryComponents: EmployeeSalaryComponent[];
};

interface EmployeeSalaryComponent {
  id: number;
  payrollEmployeeId: number;
  type: string;
  name: string;
  label: string;
  mode: string;
  isLoan: boolean;
  isActive: boolean;
  amount: string;
  calculatedAmount: string;
  companyId: number;
  createdAt: string;
  updatedAt: string;
}

// payslip list data
export type TPayslip = Partial<Payslip>;
type Payslip = {
  id: number;
  payrollId: number;
  employeeId: number;
  email: string;
  empUid: string;
  eligibility: string;
  fullName: string;
  gender: string;
  netPay: string;
  grossPay: string;
  totalAllowances: string;
  totalDeductions: string;
  tax: string;
  leaveAllowance: string;
  itf: string;
  nsitf: string;
  overtime: string;
  pension: string;
  thirteenthMonthSalary: string;
  costCentre: string;
  currency: string;
  exchangeRate: string;
  ytdNet: string;
  ytdGross: string;
  ytdTax: string;
  phoneNumber: string;
  branch: string;
  department: string;
  designation: string;
  accountNumber: string;
  bankName: string;
  bankCode: string;
  hourlyRate?: any;
  hoursCompleted: number;
  itfAuthority: string;
  itfId: string;
  nin: string;
  nsitfAuthority: string;
  nsitfId: string;
  pensionAdministrator: string;
  pensionId: string;
  taxAuthorityName: string;
  taxId: string;
  payrollType: string;
  confirmedAt: string;
  isActive: boolean;
  companyId: number;
  createdAt: string;
  updatedAt: string;
  payroll: Payroll;
};

interface Payroll {
  totalAllowances: number;
  totalDeductions: number;
  totalNetPay: number;
  totalGrossPay: number;
  totalTax: number;
  id: number;
  schemeId: number;
  name: string;
  label: string;
  date: string;
  description: string;
  frequency: string;
  status: string;
  costCentreId?: number;
  companyId: number;
  createdAt: string;
  updatedAt: string;
  scheme: Scheme;
}

interface Scheme {
  id: number;
  name: string;
  type: string;
  frequency: string;
  allowDisbursement: boolean;
  disbursement?: any;
  costCentreId?: number;
  allowApproval: boolean;
  workflowId: number;
  issuePayslip: boolean;
  projectId?: any;
  runAutomatically: boolean;
  automaticRunDay?: any;
  companyId: number;
  createdAt: string;
  updatedAt: string;
}
