export const MICROSERVICE_ENDPOINTS = {
  UTILITY: process.env.REACT_APP_UTILITY_BASE_URL,
  AUTHENTICATION: process.env.REACT_APP_AUTHENTICATION_BASE_URL,
  NOTIFICATION: process.env.REACT_APP_NOTIFICATION_BASE_URL,
};

export const APP_AUTHENTICATION_PARAMETERS = {
  SESSION_TIME: process.env.REACT_APP_SESSION_TIME,
  TOKEN_EXPIRY_TIME: process.env.REACT_APP_TOKEN_EXPIRY_TIME,
  TOKEN_INTERVAL_TIME: process.env.REACT_APP_TOKEN_INTERVAL_TIME,
};
